name: Promote to Production

on:
  workflow_run:
    workflows: ["Deploy to Vercel"]
    branches: ["dev"]
    types:
      - completed

jobs:
  promote:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Fetch dev branch
        run: git fetch origin dev

      - name: Check for changes between main and dev
        id: check_changes
        run: |
          DIFF=$(git diff --name-only main origin/dev)
          echo "::set-output name=has_changes::$(if [ -n "$DIFF" ]; then echo "true"; else echo "false"; fi)"

      - name: Merge dev into main (if changes exist)
        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git merge --no-ff --no-edit origin/dev

      - name: Push changes to main
        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
        run: |
          git push origin main
